export enum PostsTypes {
  GET_USER_POSTS = '@PostsTypes/GET_USER_POSTS',
  GET_USER_POSTS_SUCCEEDED = '@PostsTypes/GET_USER_POSTS_SUCCEEDED',
  GET_USER_POSTS_FAILED = '@PostsTypes/GET_USER_POSTS_FAILED',

  GET_POST_DETAIL = '@PostTypoes/GET_POST_DETAIL',
  GET_POST_DETAIL_SUCCEEDED = '@PostTypoes/GET_POST_DETAIL_SUCCEEDED',
  GET_POST_DETAIL_FAILED = '@PostTypoes/GET_POST_DETAIL_FAILED',

  DELETE_POST = '@PostTypoes/DELETE_POST',
  DELETE_POST_SUCCEEDED = '@PostTypoes/DELETE_POST_SUCCEEDED',
  DELETE_POST_FAILED = '@PostTypoes/DELETE_POST_FAILED',

  EDIT_POST = '@PostTypoes/EDIT_POST',
  EDIT_POST_SUCCEEDED = '@PostTypoes/EDIT_POST_SUCCEEDED',
  EDIT_POST_FAILED = '@PostTypoes/EDIT_POST_FAILED',

  CREATE_POST = '@PostTypoes/CREATE_POST',
  CREATE_POST_SUCCEEDED = '@PostTypoes/CREATE_POST_SUCCEEDED',
  CREATE_POST_FAILED = '@PostTypoes/CREATE_POST_FAILED',
}
