export enum UsersTypes {
  GET_USERS_REQUEST = '@UsersTypes/GET_USERS_REQUEST',
  GET_USERS_REQUEST_SUCCEEDED = '@UsersTypes/GET_USERS_REQUEST_SUCCEEDED',
  GET_USERS_REQUEST_FAILED = '@UsersTypes/GET_USERS_REQUEST_FAILED',
}
