export enum UserDetailTypes {
  GET_USER_DETAIL_REQUEST = '@UserDetailTypes/GET_USER_DETAIL_REQUEST',
  GET_USER_DETAIL_REQUEST_SUCCEEDED = '@UserDetailTypes/GET_USER_DETAIL_REQUEST_SUCCEEDED',
  GET_USER_DETAIL_REQUEST_FAILED = '@UserDetailTypes/GET_USER_DETAIL_REQUEST_FAILED',
}
